sudo: required
services:
    - docker

before_install:
    - docker build -t jamesw201/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jamesw201/react-test npm test

after_success:
    - docker build -t jamesw201/multi-client ./client
    - docker build -t jamesw201/multi-nginx ./nginx
    - docker build -t jamesw201/multi-server ./server
    - docker build -t jamesw201/multi-worker ./worker
    # Log in to docker hub cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to docker hub
    - docker push jamesw201/multi-client
    - docker push jamesw201/multi-nginx
    - docker push jamesw201/multi-server
    - docker push jamesw201/multi-worker